name: Build & Deploy Docker Infraviewer X64

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra-viewer
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push base image
        run: docker build . -t staijn/infraviewer:nx-base
      - name: Build sub-application images
        run: docker-compose build
      - name: Push sub-application images
        run: docker-compose push
