@startuml
left to right direction

skinparam usecase {
  BackgroundColor FloralWhite
  BorderColor Black
  ArrowColor Black
}


skinparam actor {
  BackgroundColor FloralWhite
  BorderColor Black
  ArrowColor Black
}

actor Ambtenaar as a

rectangle  {
  usecase "Opvragen informatie geografische locatie" as UC1
}

a --> UC1
@enduml
